### ISSUE TITLE
Preview image

### ISSUE THREAD

**Issue by parsampsh** [sami2020pro/vscode-pashmak#2]
I think there is a issue with preview image. The variables are not highlighted in that. I don't have problem with the variables and works for me. What is the matter?

**Comment by sami2020pro** [comment]
You can use this [repo](https://github.com/Dart-Code/Dart-Code/blob/master/syntaxes/dart.json) for a convenient example.

**Comment by sami2020pro** [comment]
and we can add a **snippet** and a **linter**.

**Comment by sami2020pro** [comment]
[official document](https://code.visualstudio.com/api/language-extensions/s)

**Comment by sami2020pro** [comment]
[official document](https://code.visualstudio.com/api/)

**Comment by parsampsh** [comment]
Yes. i means variables are not highlighted in the preview image in the readme but i have no same problem and variables are highlighted. anyway its not important :)
