### ISSUE TITLE
Hard Fork

### ISSUE THREAD

**Issue by parsampsh** [sami2020pro/vscode-pashmak#4]
Hello @sami2020pro 
I maked a **HARD FORK** from this project in `pashmaklang/vscode-pashmak`. This is for making development speed faster. 
If you like to access to this hard fork, I'll send a invitation for you to access this repository.

**Comment by sami2020pro** [comment]
You did a good job, but why didn't you let me transfer project?

**Comment by parsampsh** [comment]
> You did a good job, but why didn't you let me transfer project?

Well, anyway its not different :)

**Comment by sami2020pro** [comment]
OK 👍
I will archive this project and link to `pashmaklang/vscode-pashmak`.

**Comment by parsampsh** [comment]
> OK +1
> I will archive this project and link to `pashmaklang/vscode-pashmak`.

Thanks.

**Comment by parsampsh** [comment]
Also i sent a PR for https://github.com/github/linguist for adding the pashmak highlighter to github, but they said minimum required popularity for the language should be 200 unique repo/user. they said after passing the minimum requirement, i re-open the PR.
https://github.com/github/linguist/pull/5218

**Comment by amirghazi87** [comment]
How many pashmak has user/repo ?

**Comment by parsampsh** [comment]
> How many pashmak has user/repo ?

https://github.com/github/linguist/pull/5218#issuecomment-780418120
